"""Make a fluffy summary similar to the illumina nipt output"""

from pathlib import Path
from typing import Iterator

from fluffy.constants import ILLLUMINA_REPORT_HEADER


def make_summary(fluffy_out: Path, configs: dict, samples: Iterator[dict]) -> list:
    """Create a summary that corresponds to the illumina output

    Parse output files and store the content for a report in a list
    """
    output_header = [
        "SampleID",
        "SampleType",
        "Flowcell",
        "Description",
        "SampleProject",
        "IndexID1",
        "Index1",
        "IndexID2",
        "Index2",
        "Well",
        "Library_nM",
        "QCFlag",
        "QCFailure",
        "QCWarning",
        "Zscore_13",
        "Zscore_18",
        "Zscore_21",
        "Zscore_X",
        "Zscore_Y",
        "Ratio_13",
        "Ratio_18",
        "Ratio_21",
        "Ratio_X",
        "Ratio_Y",
        "Clusters",
        "TotalReads2Clusters",
        "MaxMisindexedReads2Clusters",
        "IndexedReads",
        "TotalIndexedReads2Clusters",
        "Tags",
        "NonExcludedSites",
        "NonExcludedSites2Tags",
        "Tags2IndexedReads",
        "PerfectMatchTags2Tags",
        "GCBias",
        "GCR2",
        "NCD_13",
        "NCD_18",
        "NCD_21",
        "NCD_X",
        "NCD_Y",
        "Chr1_Coverage",
        "Chr2_Coverage",
        "Chr3_Coverage",
        "Chr4_Coverage",
        "Chr5_Coverage",
        "Chr6_Coverage",
        "Chr7_Coverage",
        "Chr8_Coverage",
        "Chr9_Coverage",
        "Chr10_Coverage",
        "Chr11_Coverage",
        "Chr12_Coverage",
        "Chr13_Coverage",
        "Chr14_Coverage",
        "Chr15_Coverage",
        "Chr16_Coverage",
        "Chr17_Coverage",
        "Chr18_Coverage",
        "Chr19_Coverage",
        "Chr20_Coverage",
        "Chr21_Coverage",
        "Chr22_Coverage",
        "ChrX_Coverage",
        "ChrY_Coverage",
        "Chr1",
        "Chr2",
        "Chr3",
        "Chr4",
        "Chr5",
        "Chr6",
        "Chr7",
        "Chr8",
        "Chr9",
        "Chr10",
        "Chr11",
        "Chr12",
        "Chr13",
        "Chr14",
        "Chr15",
        "Chr16",
        "Chr17",
        "Chr18",
        "Chr19",
        "Chr20",
        "Chr21",
        "Chr22",
        "ChrX",
        "ChrY",
        "Median_13",
        "Median_18",
        "Median_21",
        "Median_X",
        "Median_Y",
        "Stdev_13",
        "Stdev_18",
        "Stdev_21",
        "Stdev_X",
        "Stdev_Y",
        "FF_Formatted",
        "FFY",
        "FFX",
        "DuplicationRate",
        "Bin2BinVariance",
        "UnfilteredCNVcalls",
        "CNVSegment",
    ]

    content = []
    min_cnv = config["summary"]["mincnv"]
    z_score = config["summary"]["zscore"]

    return content
